### ISSUE TITLE
Build trouble

### ISSUE THREAD

**Issue by simone-hochgreb** [rougier/bootstrap-rst#37]
I tried building it with python 2.7 and 3, and I get the following: 
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
make: *** [CSS.html] Error 1

Ideas?

**Comment by akuroiwa** [comment]
In [my carousel branch](https://github.com/rougier/bootstrap-rst/pull/36), I used the method `update()` to resolve [a similar issue](https://stackoverflow.com/questions/13361510/typeerror-unsupported-operand-types-for-dict-items-and-dict-items).  Please see the class Container of `directives.py` in [the branch](https://github.com/akuroiwa/bootstrap-rst/tree/carousel).

And could you find the line number of the bug and show us the revision number of Python?

**Comment by simone-hochgreb** [comment]
Thank you. 

I have used 3.5 and 2.7. 

Here is the traceback: 

Traceback (most recent call last):
  File "./bootstrap.py", line 429, in <module>
    main()
  File "./bootstrap.py", line 393, in main
    description=description)
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/core.py", line 352, in publish_cmdline
    config_section=config_section, enable_exit_status=enable_exit_status)
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/writers/_html_base.py", line 71, in translate
    self.document.walkabout(visitor)
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/writers/html4css1/__init__.py", line 764, in visit_tbody
    self.write_colspecs()
  File "/Applications/anaconda/lib/python3.5/site-packages/docutils/writers/html4css1/__init__.py", line 288, in write_colspecs
    width += node['colwidth']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
make: *** [CSS.html] Error 1

**Comment by simone-hochgreb** [comment]
Thank you. 

I can say that 'make *.html’ works fine, but make all fails in the mode indicated. 

I will try to work with the individual pages for now while I try to figure out the problem. 

Simone

**Comment by rougier** [comment]
The carousel branch has been merged. If you test with the newest version, that might work.

**Comment by akuroiwa** [comment]
It seems that you installed [docutils through Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues/1638).  I don't know about Anaconda, but I would recommend using pip command instead of it.

I guess you might use an old version of docutils.

**Comment by simone-hochgreb** [comment]
Thank you. 

I updated python using conda to the latest docutils, and it is no longer complaining. Success!
